openapi: 3.1.0
info:
  title: "DummyImage API"
  version: "1.0.0"
  description: "텍스트를 포함한 플레이스홀더 이미지를 생성하는 퍼블릭 API입니다. 크기, 배경색, 전경색, 텍스트 등을 지정하여 이미지 생성이 가능합니다."
servers:
  - url: "https://dummyimage.com"
paths:
  /{size}:
    get:
      summary: "크기 기반 이미지 생성"
      description: "지정된 이미지 크기와 색상, 텍스트를 기반으로 PNG 이미지를 반환합니다."
      operationId: getDummyImage
      parameters:
        - name: size
          in: path
          required: true
          description: "이미지 크기 (예: 300x200)"
          schema:
            type: string
            pattern: "^\\d+x\\d+$"
        - name: bgcolor
          in: query
          description: "배경색 (hex 코드, 예: ff6600)"
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{6}$"
        - name: fgcolor
          in: query
          description: "전경색/글자색 (hex 코드, 예: ffffff)"
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{6}$"
        - name: text
          in: query
          description: "이미지 안에 표시할 텍스트"
          schema:
            type: string
      responses:
        "200":
          description: "플레이스홀더 이미지 반환 (image/png)"
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: "잘못된 파라미터 입력"
