openapi: 3.1.0
info:
  title: "Lorem Picsum 이미지 API"
  description: "무작위 또는 특정 ID의 플레이스홀더 이미지를 제공하는 무료 이미지 API입니다."
  version: "1.0.0"
servers:
  - url: "https://picsum.photos"
paths:
  /{width}/{height}:
    get:
      operationId: getRandomImage
      tags:
        - image
      summary: "무작위 이미지 가져오기"
      description: "지정한 크기의 무작위 이미지를 반환합니다. 블러 및 흑백 옵션을 선택할 수 있습니다."
      parameters:
        - name: width
          in: path
          required: true
          description: "이미지의 가로 크기 (px)"
          schema:
            type: integer
        - name: height
          in: path
          required: true
          description: "이미지의 세로 크기 (px)"
          schema:
            type: integer
        - name: blur
          in: query
          description: "블러 필터 적용 정도 (1 이상 시 적용)"
          schema:
            type: integer
        - name: grayscale
          in: query
          description: "흑백 이미지로 반환할지 여부 (true 시 흑백)"
          schema:
            type: boolean
      responses:
        "302":
          description: "무작위 이미지로 리디렉션합니다"
        "400":
          description: "잘못된 width 또는 height 값"
  /id/{id}/{width}/{height}:
    get:
      operationId: getImageById
      tags:
        - image
      summary: "ID로 이미지 가져오기"
      description: "특정 ID의 이미지를 지정된 크기로 반환합니다. 블러 및 흑백 필터 옵션을 지원합니다."
      parameters:
        - name: id
          in: path
          required: true
          description: "이미지의 고유 ID"
          schema:
            type: integer
        - name: width
          in: path
          required: true
          description: "이미지의 가로 크기 (px)"
          schema:
            type: integer
        - name: height
          in: path
          required: true
          description: "이미지의 세로 크기 (px)"
          schema:
            type: integer
        - name: blur
          in: query
          description: "블러 필터 적용 정도 (1 이상 시 적용)"
          schema:
            type: integer
        - name: grayscale
          in: query
          description: "흑백 이미지로 반환할지 여부 (true 시 흑백)"
          schema:
            type: boolean
      responses:
        "302":
          description: "해당 ID의 이미지로 리디렉션합니다"
  /v2/list:
    get:
      operationId: listImages
      tags:
        - image
      summary: "이미지 목록 조회"
      description: "사용 가능한 이미지의 메타데이터 목록을 페이지 단위로 조회합니다."
      parameters:
        - name: page
          in: query
          description: "페이지 번호 (기본값: 1)"
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: "한 페이지에 가져올 이미지 수 (기본값: 30)"
          schema:
            type: integer
            default: 30
      responses:
        "200":
          description: "이미지 메타데이터 리스트를 반환합니다"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: "이미지 고유 ID"
                    author:
                      type: string
                      description: "이미지 작성자 이름"
                    width:
                      type: integer
                      description: "원본 이미지의 가로 크기 (px)"
                    height:
                      type: integer
                      description: "원본 이미지의 세로 크기 (px)"
                    url:
                      type: string
                      description: "원본 이미지 상세 정보 페이지 URL"
                    download_url:
                      type: string
                      description: "직접 다운로드 가능한 이미지 URL"
