---
openapi: 3.0.3
info:
  title: Image Background Remove API
  version: 1.0.0
  description: Base64 또는 URL로 이미지를 입력받아 배경을 제거합니다. MCP로 호환됩니다.
servers:
- url: https://api.remove.bg/v1.0
paths:
  "/removebg":
    get:
      summary: 이미지 배경 제거 실행
      description: image_url 또는 image_file_b64 중 하나를 입력하면 배경이 제거된 이미지를 반환합니다.
      operationId: removeBackground
      parameters:
      - name: image_url
        in: query
        description: 외부 이미지 URL (선택)
        required: false
        schema:
          type: string
          format: uri
      - name: image_file_b64
        in: query
        description: Base64 인코딩된 이미지 데이터 (선택)
        required: false
        schema:
          type: string
      - name: size
        in: query
        description: 해상도 설정
        schema:
          type: string
          enum:
          - preview
          - full
          - auto
          default: auto
      - name: type
        in: query
        description: 전경 객체 타입
        schema:
          type: string
          enum:
          - auto
          - person
          - product
          - car
          default: auto
      - name: format
        in: query
        description: 출력 이미지 포맷
        schema:
          type: string
          enum:
          - auto
          - png
          - jpg
          default: auto
      responses:
        '200':
          description: 성공 시 결과 이미지 (base64 인코딩된 JSON)
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RemoveBgJsonResponse"
components:
  schemas:
    RemoveBgJsonResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            result_b64:
              type: string
              description: Base64 인코딩된 결과 이미지
            foreground_top:
              type: integer
            foreground_left:
              type: integer
            foreground_width:
              type: integer
            foreground_height:
              type: integer
