openapi: 3.0.3
info:
  title: removebg
  version: 1.0.0
  description: Base64 또는 URL로 이미지를 입력받아 배경을 제거합니다. MCP로 호환됩니다.
servers:
  - url: https://api.remove.bg/v1.0
security:
  - ApiKeyAuth: []
paths:
  /removebg:
    post:
      summary: 이미지 배경 제거 실행
      description: image_url 또는 image_file_b64 중 하나를 입력하면 배경이 제거된 이미지를 반환합니다.
      operationId: removeBackground
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - image_url
              properties:
                image_url:
                  type: string
                image_file_b64:
                  type: string
                  format: byte
                  description: 원본 이미지의 Base64 인코딩 (image_url 대신 사용 가능)
                size:
                  type: string
                  enum: [preview, full, auto]
                  default: auto
                type:
                  type: string
                  enum: [auto, person, product, car]
                  default: auto
                format:
                  type: string
                  enum: [auto, png, jpg]
                  default: auto
      responses:
        '200':
          description: 성공 시 배경이 제거된 이미지와 전경 정보 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  result_b64:
                    type: string
                    format: byte
                    description: 배경이 제거된 이미지의 Base64 인코딩
                  foreground_top:
                    type: integer
                    description: 전경의 top 좌표
                  foreground_left:
                    type: integer
                    description: 전경의 left 좌표
                  foreground_width:
                    type: integer
                    description: 전경의 너비
                  foreground_height:
                    type: integer
                    description: 전경의 높이
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
