openapi: 3.0.3
info:
  title: "Image Background Remove API"
  version: "1.0.0"
  description: >
    "이 API는 이미지에서 배경을 자동으로 제거하는 AI 기반 이미지 처리 서비스입니다.
    사용자는 이미지 파일을 직접 업로드하거나 이미지 URL을 제공하여 배경 제거 결과를 얻을 수 있습니다.
    주로 이커머스 제품 사진 처리, SNS 썸네일 제작, 인물 이미지 배경 제거 등에 활용됩니다."

servers:
  - url: "https://www.remove.bg"

paths:
  /remove-bg/upload:
    post:
      summary: "업로드한 이미지에서 배경 제거"
      description: >
        "사용자가 로컬에 저장된 이미지를 직접 업로드하면, 서버는 해당 이미지를 분석하여 배경을 제거한 후 PNG 포맷으로 반환합니다.
        고해상도 제품 사진, 인물 사진 등의 배경 제거에 유용하며, 사용자 입력이 정확한 경우 가장 빠르고 안정적인 결과를 제공합니다."
      operationId: "removeBackgroundFromUpload"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image_file:
                  type: string
                  format: binary
                  description: "사용자가 업로드할 이미지 파일 (JPG, PNG 형식). 전경 객체가 명확히 보이는 이미지가 좋습니다."
                size:
                  type: string
                  enum: [auto, preview, full]
                  default: auto
                  description: >
                    "출력 이미지 크기 설정입니다. 'auto'는 서버가 적절히 판단하여 결정하며, 'preview'는 빠른 미리보기 용도로, 'full'은 고해상도 이미지를 의미합니다."
      responses:
        "200":
          description: "배경이 제거된 PNG 이미지가 바이너리 형태로 반환됩니다."
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: "업로드된 파일이 없거나 형식이 잘못된 경우 발생합니다."
        "401":
          description: "API 키가 누락되었거나 유효하지 않을 경우 발생합니다."
      security:
        - ApiKeyAuth: []

  /remove-bg/url:
    post:
      summary: "이미지 URL로 배경 제거"
      description: >
        "사용자가 이미지 URL을 제공하면 서버는 해당 이미지를 다운로드하여 분석한 후 배경을 제거합니다.
        외부에서 크롤링된 이미지나 CDN에 저장된 파일을 바로 처리하고자 할 때 유용합니다.
        단, 비공개 링크이거나 접근이 차단된 경우 오류가 발생할 수 있습니다."
      operationId: "removeBackgroundFromUrl"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image_url:
                  type: string
                  format: uri
                  description: "처리할 이미지의 외부 URL (http 또는 https). 접근 가능한 공개 링크여야 합니다."
                size:
                  type: string
                  enum: [auto, preview, full]
                  default: auto
                  description: "출력 이미지 크기 설정 방식 (auto, preview, full)"
      responses:
        "200":
          description: "배경이 제거된 이미지가 PNG 포맷으로 반환됩니다."
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: "유효하지 않은 URL이거나 이미지 다운로드 또는 처리 중 오류 발생"
        "401":
          description: "API 키 인증 실패"
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
